# Template: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package using Pip

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

# Cancel workflow if a new push occurs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-extras:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.12"]
        include:
          - os: macos-13
            python-version: 3.8
          - os: macos-latest
            python-version: 3.12

    steps:
    # --- INSTALLATIONS ---
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install package
      shell: bash
      run: |
        python -m pip install -e .[extras,dev]

    - name: Additional install soundfile (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libsndfile1

    - name: Additional install soundfile (macOS)
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
      run: |
        brew install libsndfile

    # --- TESTS ---
    - name: Lint with flake8
      run: |
        python -m flake8 --config .flake8 --exit-zero --show-source --statistics src

    - name: Check format with Black
      run: |
        python -m black --check --diff src

    - name: Print install info
      run: |
        torchoutil-info

    - name: Test with pytest
      run: |
        coverage run -m pytest -v

    - name: Show coverage results
      run: |
        ls -lha
        coverage report -m

  build-minimal:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.12"]
        include:
          - os: macos-13
            python-version: 3.8
          - os: macos-latest
            python-version: 3.12

    # steps:
    # # --- INSTALLATIONS ---
    # - name: Checkout repository
    #   uses: actions/checkout@v4

    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: ${{ matrix.python-version }}
    #     cache: 'pip'

    # - name: Install package
    #   shell: bash
    #   run: |
    #     python -m pip install -e .[dev]

    # - name: Additional install soundfile (Ubuntu)
    #   if: matrix.os == 'ubuntu-latest'
    #   run: |
    #     sudo apt-get install libsndfile1

    # - name: Additional install soundfile (macOS)
    #   if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
    #   run: |
    #     brew install libsndfile

    # # --- TESTS ---
    # - name: Lint with flake8
    #   run: |
    #     python -m flake8 --config .flake8 --exit-zero --show-source --statistics src

    # - name: Check format with Black
    #   run: |
    #     python -m black --check --diff src

    # - name: Print install info
    #   run: |
    #     torchoutil-info

    # - name: Test with pytest
    #   run: |
    #     coverage run -m pytest -v --ignore=./tests/test_extras_hdf.py --ignore=./tests/test_utils_pack.py --ignore=./tests/test_hub_registry.py --ignore=./tests/test_extras_numpy_functional.py --ignore=./tests/test_extras_numpy_scan_info.py

    # - name: Show coverage results
    #   run: |
    #     coverage report -m
